version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/DevExServerProject
    runas: ubuntu
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/DevExServerProject/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60